### PR TITLE
Detach arming

### PR DESCRIPTION
**Pull request by RobertSchaffer1**
@JunAishima @vshekar Changes to return a status for detector arming, rather than waiting for completion

### CODE REVIEW

**Review by JunAishima — COMMENTED** [review]
is there a good way to keep track of arming time then? sounds like it will never get measured and certainly never printed, even if it is finishing within the `arm_status.wait()` in LSDC. maybe we can print out the finishing time of arm+gov move in LSDC?

**Comment by RobertSchaffer1** [comment]
> is there a good way to keep track of arming time then? sounds like it will never get measured and certainly never printed, even if it is finishing within the `arm_status.wait()` in LSDC. maybe we can print out the finishing time of arm+gov move in LSDC?

I gave it a bit of thought when I was coding it, and unfortunately I don't really see one. Not sure how critical that is? It's tricky, because the main thread is busy with other things, and only checks the status when it's done. I could easily enough put in a check for if it lasts longer than the governor move, but without putting in a separate thread I don't see a way around it.

**Comment by JunAishima** [comment]
> > is there a good way to keep track of arming time then? sounds like it will never get measured and certainly never printed, even if it is finishing within the `arm_status.wait()` in LSDC. maybe we can print out the finishing time of arm+gov move in LSDC?
> 
> I gave it a bit of thought when I was coding it, and unfortunately I don't really see one. Not sure how critical that is? It's tricky, because the main thread is busy with other things, and only checks the status when it's done. I could easily enough put in a check for if it lasts longer than the governor move, but without putting in a separate thread I don't see a way around it.

that's kinda what I was thinking, too. will reiterate that we should put in arm+gov time in LSDC, I don't think the arming time itself is important if things are working correctly. this may bite us if we arm the detector incorrectly (such as what I had done with rasters until we noticed LONG arming times on FMX)

**Review by JunAishima — APPROVED** [review]

**Comment by RobertSchaffer1** [comment]
I forgot to mention, this one should be fine but the nyxtools will require a slightly more complex change (and testing) to run, so the change to LSDC should only be pushed to the FMX/AMX codebases for now.

**Comment by JunAishima** [comment]
@RobertSchaffer1 I could then make the base 2023-2-amxfmx.... (for the LSDC changes!)

**Pull request merged**
